# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

pod 'SwiftInstagram', '~> 1.1.1'

target 'SocialPostSearchDemo' do
   pod 'SVProgressHUD'
   pod 'AlamofireImage', '~> 3.3'
end

target 'SocialPostSearchDemoTests' do
end
